'use strict'

/**
 * Chromium stores compiled GPU shaders under userData/GPUCache. After Mesa or
 * WSL GPU stack changes (e.g. Ubuntu 24.04 → 26.04), the index can reference
 * missing or unreadable data_N files and Electron logs:
 *   ERROR:net/disk_cache/blockfile/block_files.cc:445 Failed to open .../GPUCache/data_3
 * Clearing a broken cache lets Chromium recreate it; harmless when the cache is healthy.
 */

const fsDefault = require('fs')
const os = require('os')
const path = require('path')

/** Chromium block-file cache uses data_0 … data_3 alongside index. */
const GPU_CACHE_DATA_SLOTS = 4

/**
 * @param {{ platform?: string, homedir?: string }} [opts]
 * @returns {string}
 */
function getAppConfigDir(opts = {}) {
  const platform = opts.platform || process.platform
  const home = opts.homedir || os.homedir()
  if (platform === 'darwin') {
    return path.join(home, 'Library', 'gatewizard-gui')
  }
  return path.join(home, '.config', 'gatewizard-gui')
}

/**
 * @param {string} configDir
 * @param {{ accessSync?: Function, readdirSync?: Function, rmSync?: Function, constants?: { R_OK?: number, W_OK?: number } }} [fs]
 * @returns {boolean} true when GPUCache was removed
 */
function clearCorruptedGpuCache(configDir, fs = fsDefault) {
  const gpuCache = path.join(configDir, 'GPUCache')
  try {
    fs.accessSync(gpuCache)
  } catch {
    return false
  }

  /** @param {string} reason */
  const remove = (reason) => {
    try {
      fs.rmSync(gpuCache, { recursive: true, force: true })
      return true
    } catch {
      return false
    }
  }

  let entries
  try {
    entries = fs.readdirSync(gpuCache)
  } catch {
    return remove('unreadable')
  }

  if (!entries.includes('index')) return false

  const mode = (fs.constants?.R_OK ?? 4) | (fs.constants?.W_OK ?? 2)
  for (let i = 0; i < GPU_CACHE_DATA_SLOTS; i++) {
    const dataPath = path.join(gpuCache, `data_${i}`)
    try {
      fs.accessSync(dataPath, mode)
    } catch {
      return remove(`missing-or-locked:data_${i}`)
    }
  }

  return false
}

/** POSIX sh for the packaged Linux launcher (before Electron exec). */
function buildGpuCacheShell() {
  return `
# Drop stale Chromium GPU shader cache (generated by gpu-cache.cjs)
gw_gpu_cache="\${XDG_CONFIG_HOME:-\$HOME/.config}/gatewizard-gui/GPUCache"
if [ -d "\$gw_gpu_cache" ] && [ -f "\$gw_gpu_cache/index" ]; then
  gw_cache_bad=0
  for gw_i in 0 1 2 3; do
    if [ ! -r "\$gw_gpu_cache/data_\$gw_i" ] || [ ! -w "\$gw_gpu_cache/data_\$gw_i" ]; then
      gw_cache_bad=1
      break
    fi
  done
  if [ "\$gw_cache_bad" -eq 1 ]; then
    rm -rf "\$gw_gpu_cache" 2>/dev/null || true
  fi
fi
`
}

module.exports = {
  GPU_CACHE_DATA_SLOTS,
  getAppConfigDir,
  clearCorruptedGpuCache,
  buildGpuCacheShell
}
